# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3051923e401328c94ec0a5fead8f8a5f89be0f2e0ef0c62db3b57831a2dc2b1ca07adace89376a0f27d39c9d477da6e955eb1b7e6a7f32e02bd22287cc2b50f8

test:
  secret_key_base: 98f4c5cc042d731b20975e91438dc3479f607c198720960baa0f9af8f6d8395bbb4a80ea849d1a046e16c3347272b64e5e8322629a9cad7338d9068fb56271eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
